erDiagram
    CAR ||--o{ NAMED-DRIVER : allows
    CAR ||--|| INSURANCE : has
    CAR {
        string registrationNumber PK
        string make
        string model
        string[] parts
    }
    PERSON ||--o{ NAMED-DRIVER : is
    PERSON {
        string driversLicense PK "The license #"
        string(99) firstName "Only 99 characters are allowed"
        string lastName
        string phone UK
        int age
        int insurancePolicyId FK
    }
    NAMED-DRIVER {
        string carRegistrationNumber PK, FK
        string driverLicence PK, FK
    }
    INSURANCE {
        int insurancePolicyId PK, FK
        string policyName
        bool isActive
        int deductible
    }
    MANUFACTURER only one to zero or more CAR : makes